server: 
    port: 8080
spring: 
    datasource: 
        name: poll
        url: jdbc:mysql://localhost:3306/poll2.0?useUnicode=true&characterEncoding=UTF-8&useSSL=false
        username: root
        password: 123456  


