#####使用哪个环境 pro生成环境  dev开发环境########
spring:
    profiles: 
        active: dev
########## 静态资源访问配置 ###########
    mvc: 
        static-path-pattern: /**
    resources:
        static-locations: classpath:/static/
    
###########  MVC视图解析配置  ###########
spring.mvc.view.prefix: classpath:/templates/
spring.mvc.view.suffix: .html
spring.mvc.date-format: yyyy-MM-dd


mybatis: 
    config-locations: classpath:mybatis-config.xml
    mapper-locations: classpath:mapper/*.xml  

# 热部署开关，false即不启用热部署
spring.devtools.restart.enabled: true

# 指定热部署的目录
spring.devtools.restart.additional-paths: src/main/

# 指定目录不更新
spring.devtools.restart.exclude: test/**

