server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://139.199.64.253:3306/poll2.0?useUnicode=true&characterEncoding=utf-8&useSSL=false
    data-username: root
    data-password: 123456
